# Project: Tetris
# Makefile created by Dev-C++ 6.5

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = acllib.o main.o map.o draw.o recore.o
LINKOBJ  = acllib.o main.o map.o draw.o recore.o
LIBS     = -L"D:/soft/Dev-Cpp/MinGW32/lib" -L"D:/soft/Dev-Cpp/MinGW32/i686-w64-mingw32/lib" -static-libstdc++ -static-libgcc -mwindows D:/soft/Dev-Cpp/MinGW32/i686-w64-mingw32/lib/libkernel32.a D:/soft/Dev-Cpp/MinGW32/i686-w64-mingw32/lib/libuser32.a D:/soft/Dev-Cpp/MinGW32/i686-w64-mingw32/lib/libgdi32.a D:/soft/Dev-Cpp/MinGW32/i686-w64-mingw32/lib/libole32.a D:/soft/Dev-Cpp/MinGW32/i686-w64-mingw32/lib/liboleaut32.a D:/soft/Dev-Cpp/MinGW32/i686-w64-mingw32/lib/libuuid.a D:/soft/Dev-Cpp/MinGW32/i686-w64-mingw32/lib/libwinmm.a D:/soft/Dev-Cpp/MinGW32/i686-w64-mingw32/lib/libmsimg32.a
INCS     = -I"D:/soft/Dev-Cpp/MinGW32/include" -I"D:/soft/Dev-Cpp/MinGW32/i686-w64-mingw32/include" -I"D:/soft/Dev-Cpp/MinGW32/lib/gcc/i686-w64-mingw32/10.2.0/include" -I"D:/soft/Dev-Cpp/MinGW32/lib/gcc/i686-w64-mingw32/10.2.0/include-fixed"
CXXINCS  = -I"D:/soft/Dev-Cpp/MinGW32/include" -I"D:/soft/Dev-Cpp/MinGW32/i686-w64-mingw32/include" -I"D:/soft/Dev-Cpp/MinGW32/lib/gcc/i686-w64-mingw32/10.2.0/include" -I"D:/soft/Dev-Cpp/MinGW32/lib/gcc/i686-w64-mingw32/10.2.0/include-fixed" -I"D:/soft/Dev-Cpp/MinGW32/include/c++/10.2.0" -I"D:/soft/Dev-Cpp/MinGW32/include/c++/10.2.0/i686-w64-mingw32" -I"D:/soft/Dev-Cpp/MinGW32/include/c++/10.2.0/backward"
BIN      = Tetris.exe
CXXFLAGS = $(CXXINCS) -Werror
ENCODINGS = -finput-charset=utf-8 -fexec-charset=gbk
CFLAGS   = $(INCS) -Werror
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

acllib.o: acllib.c acllib.h
	$(CC) -c acllib.c -o acllib.o $(CFLAGS)  $(ENCODINGS) 

main.o: main.c acllib.h draw.h main.h map.h recore.h
	$(CC) -c main.c -o main.o $(CFLAGS)  $(ENCODINGS) 

map.o: map.c draw.h main.h
	$(CC) -c map.c -o map.o $(CFLAGS)  $(ENCODINGS) 

draw.o: draw.c acllib.h main.h
	$(CC) -c draw.c -o draw.o $(CFLAGS)  $(ENCODINGS) 

recore.o: recore.c main.h
	$(CC) -c recore.c -o recore.o $(CFLAGS) 
